#version 460

#define INPUT 0
#define OUTPUT 1

layout(local_size_x = 1024) in;

layout(set = 0, binding = 0) buffer testSsob {
    uint data[];
} test[2];


void main() {
    for(uint i = 0; i < 2; ++i) {
        uint index = i * gl_WorkGroupSize.x + gl_GlobalInvocationID.x;
        if(test[INPUT].data[index] == 1 )  {
            continue;
        }
        barrier();
        test[OUTPUT].data[gl_GlobalInvocationID.x] = 1;
    }
}