#version 460

#define INPUT 0
#define OUTPUT 1

layout(local_size_x = 1024) in;

layout(set = 0, binding = 0) buffer testSsob {
    uint data[];
} test[2];

shared uint mutex;
shared bool state;

void main() {
    if(gl_GlobalInvocationID.x == 0) {
        mutex = 0;
        state = false;
    }
    barrier();

    if(atomicCompSwap(mutex, 0, 1) == 0){
        state = true;
    }
    barrier();
    if(state) {
        test[OUTPUT].data[gl_GlobalInvocationID.x] = 2;
    }
}