#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#include "../common.glsl"

layout(set = 1, binding = 0) uniform sampler3D vector_field_u;
layout(set = 2, binding = 0) uniform sampler3D vector_field_v;
layout(set = 3, binding = 0) uniform sampler3D pressure_field;
layout(set = 4, binding = 2) uniform writeonly image3D div_free_vector_field_u;
layout(set = 5, binding = 2) uniform writeonly image3D div_free_vector_field_v;

float p(vec2 xy) {
    return texture(pressure_field, vec3(xy, 0.5)).x;
}

vec2 w(vec4 uv) {
    vec2 u;
    u.x = texture(vector_field_u, vec3(uv.xy, 0.5)).x;
    u.y = texture(vector_field_v, vec3(uv.zw, 0.5)).x;
    return u;
}

vec2 pg(vec2 uv){
    float dudx = (p(uv + dx.xy) - p(uv))/dx.x;
    float dudy = (p(uv + dy.xy) - p(uv))/dy.y;

    return vec2(dudx, dudy);
}



void main() {
    vec4 vuv;

    vuv.xy = (vec2(gid) + 0.5)/vec2(textureSize(vector_field_u, 0).xy);
    vuv.zw = (vec2(gid) + 0.5)/vec2(textureSize(vector_field_v, 0).xy);

    vec2 uv = (vec2(gid) + 0.5)/vec2(textureSize(pressure_field, 0).xy);

    vec2 u = w(vuv) - pg(uv);

    imageStore(div_free_vector_field_u, gid3, vec4(u.x));
    imageStore(div_free_vector_field_v, gid3, vec4(u.y));
}
