#pragma once

#include <glm/glm.hpp>

constexpr int TRANSMITTANCE_TEXTURE_WIDTH = 256;
constexpr int TRANSMITTANCE_TEXTURE_HEIGHT = 64;
constexpr int SCATTERING_TEXTURE_R_SIZE = 32;
constexpr int SCATTERING_TEXTURE_MU_SIZE = 128;
constexpr int SCATTERING_TEXTURE_MU_S_SIZE = 32;
constexpr int SCATTERING_TEXTURE_NU_SIZE = 8;
constexpr int IRRADIANCE_TEXTURE_WIDTH = 64;
constexpr int IRRADIANCE_TEXTURE_HEIGHT = 16;
constexpr float MAX_SUN_ZENITH_ANGLE = glm::radians(120.f);
constexpr int DENSITY_PROFILE_RAYLEIGH = 0;
constexpr int DENSITY_PROFILE_MIE = 1;
constexpr int DENSITY_PROFILE_OZONE = 2;
constexpr int NUM_DENSITY_PROFILES  = 4;
constexpr int BOTTOM = 0;
constexpr int TOP = 1;

constexpr int SCATTERING_TEXTURE_WIDTH = SCATTERING_TEXTURE_NU_SIZE * SCATTERING_TEXTURE_MU_S_SIZE;
constexpr int SCATTERING_TEXTURE_HEIGHT = SCATTERING_TEXTURE_MU_SIZE;
constexpr int SCATTERING_TEXTURE_DEPTH = SCATTERING_TEXTURE_R_SIZE;