#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_samplerless_texture_functions : enable

#define COLLISION_SET 4
#include "common.glsl"

layout(local_size_x = 32, local_size_y = 32) in;

layout(set = 1, binding = 0) uniform sampler3D source_field;
layout(set = 2, binding = 0) uniform sampler3D accumulated_field;
layout(set = 3, binding = 2) uniform writeonly image3D destination_field;

void main() {
    if(outOfBounds()) return;

    vec3 uv = get_uvw();

    vec4 result = texture(source_field, uv) * dt + texture(accumulated_field, uv);

    imageStore(destination_field, gid3, result);
}
