#version 460

#define ACTION_COMBINE 0
#define ACTION_SPLIT 1

#include "common.glsl"

layout(local_size_x = 8, local_size_y = 8) in;

layout(set = 1, binding = 2, r32f) uniform image3D vector_field_u;
layout(set = 2, binding = 2, r32f) uniform image3D vector_field_v;
layout(set = 3, binding = 2, rgba32f) uniform image2D combinded_vector_field;

layout(push_constant) uniform Constants {
    uint action;
};

vec4 v = vec4(0);

void main() {
    if(outOfBounds()) return;

    if(action == ACTION_COMBINE) {
        v.x = imageLoad(vector_field_u, gid3).x;
        v.y = imageLoad(vector_field_v, gid3).x;

        imageStore(combinded_vector_field, gid, v);
    }

    if(action == ACTION_SPLIT) {
        v = imageLoad(combinded_vector_field, gid);
        imageStore(vector_field_u, gid3, vec4(v.x));
        imageStore(vector_field_v, gid3, vec4(v.y));
    }
}
