#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 32, local_size_y = 32) in;


#define COLLISION_SET 5
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler2D vector_field_u;
layout(set = 2, binding = 0) uniform sampler2D vector_field_v;

layout(set = 3, binding = 2) uniform writeonly image2D vector_field_u_out;
layout(set = 4, binding = 2) uniform writeonly image2D vector_field_v_out;

vec2 loadVectorField(ivec2 gid) {
    vec2 u;
    u.x = texelFetch(vector_field_u, gid, 0).x;
    u.y = texelFetch(vector_field_v, gid, 0).x;

    return u;
}

void updateVectorField(ivec2 gid, vec2 u) {
    imageStore(vector_field_u_out, gid, vec4(u.x));
    imageStore(vector_field_v_out, gid, vec4(u.y));
}


void main() {
    if(outOfBounds()) return;

    vec2 u = loadVectorField(gid);

    uint type = BOUNDARY_TYPE_INVALID;
    if (sampleBoundary(gid, type) < 0) {
        if(type == BOUNDARY_TYPE_WALL) {
            u = vec2(0);
        }

    }

    updateVectorField(gid, u);
}