#version 460

#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable
#extension GL_EXT_debug_printf : enable

layout(local_size_x = 8, local_size_y = 8) in;


#define COLLISION_SET 7
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler3D vector_field_u;
layout(set = 2, binding = 0) uniform sampler3D vector_field_v;
layout(set = 3, binding = 0) uniform sampler3D vector_field_w;

layout(set = 4, binding = 2) uniform writeonly image3D vector_field_u_out;
layout(set = 5, binding = 2) uniform writeonly image3D vector_field_v_out;
layout(set = 6, binding = 2) uniform writeonly image3D vector_field_w_out;

vec3 loadVectorField(ivec3 coord) {
    coord = collisionSampleCoord(coord);
    vec3 u;
    u.x = texelFetch(vector_field_u, coord, 0).x;
    u.y = texelFetch(vector_field_v, coord, 0).x;
    u.z = is3D ? texelFetch(vector_field_w, coord, 0).x : 0.0;

    return u;
}

vec3 getGradient(ivec3 coord) {
    float L = sampleBoundary((coord - ivec3(1, 0, 0)));
    float R = sampleBoundary((coord + ivec3(1, 0, 0)));
    float B = sampleBoundary((coord - ivec3(0, 1, 0)));
    float T = sampleBoundary((coord + ivec3(0, 1, 0)));
    float D = is3D ? sampleBoundary((coord - ivec3(0, 0, 1))) : 0.0;
    float U = is3D ? sampleBoundary((coord + ivec3(0, 0, 1))) : 0.0;
    return vec3(R - L, T - B, U - D);
}

void updateVectorField(ivec3 cell, vec3 u) {
    imageStore(vector_field_u_out, cell, vec4(u.x));
    imageStore(vector_field_v_out, cell, vec4(u.y));
    imageStore(vector_field_w_out, cell, vec4(u.z));
}


void main() {
    if(outOfBounds()) return;

    vec3 u = loadVectorField(gid3);

    uint type = BOUNDARY_TYPE_INVALID;
    if (sampleBoundary(gid3, type) < 0) {
        vec3 grad = getGradient(gid3);
        float mag = length(grad);

        if(mag <= 1e-6) {
            updateVectorField(gid3, vec3(0));
            return;
        }

        vec3 n = (type == BOUNDARY_TYPE_SDF ? grad : -grad) / mag;

        ivec3 offset;
        if (abs(n.x) > abs(n.y) && (!is3D || abs(n.x) > abs(n.z))) {
            offset = ivec3(int(sign(n.x)), 0, 0);
        } else if (!is3D || abs(n.y) > abs(n.z)) {
            offset = ivec3(0, int(sign(n.y)), 0);
        } else {
            offset = ivec3(0, 0, int(sign(n.z)));
        }

        ivec3 neighbour = gid3 + offset;

        if ((!wrappingEnabled && outOfBounds(neighbour)) || isInsideWall(neighbour)) {
            updateVectorField(gid3, vec3(0));
            return;
        }

        vec3 uv = vec3(gid3)/vec3(grid_size);
        vec3 p = mix(vec3(0), vec3(1, 2, 1), uv);
//        debugPrintfEXT("id: [%.5f, %.5f, %.5f] hit collider\n", p.x, p.y, p.z);
        vec3 v = vec3(sampleColliderVelocity(gid3), 0.0);
        u = loadVectorField(neighbour);
        vec3 u_rel = (u - v);
        u = u_rel - dot(u_rel, n) * n;
    }

    updateVectorField(gid3, u);
}
