#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#define COLLISION_SET 6
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler2D vector_field_u;
layout(set = 2, binding = 0) uniform sampler2D vector_field_v;
layout(set = 3, binding = 0) uniform sampler2D pressure_field;
layout(set = 4, binding = 2) uniform writeonly image2D div_free_vector_field_u;
layout(set = 5, binding = 2) uniform writeonly image2D div_free_vector_field_v;

float p(ivec2 cell) {
    return texelFetch(pressure_field, collisionSampleCoord(cell), 0).x;
}

float p(ivec2 centerCell, ivec2 sampleCell) {
    if (isInsideWall(sampleCell) || outOfBounds(sampleCell)) {
        return p(centerCell);
    }

    return p(sampleCell);
}

vec2 w(vec2 xy) {
    vec2 u;
    u.x = texture(vector_field_u, xy).x;
    u.y = texture(vector_field_v, xy).x;
    return u;
}

vec2 pg(ivec2 cell){
    float dudx = (p(cell, cell + ivec2(1, 0)) - p(cell, cell - ivec2(1, 0)))/(2*dx.x);
    float dudy = (p(cell, cell + ivec2(0, 1)) - p(cell, cell - ivec2(0, 1)))/(2*dy.y);

    return vec2(dudx, dudy);
}

void main() {
    if(outOfBounds()) return;


    vec2 u = vec2(0);
    if(!isInsideWall(gid)) {
        vec2 uv = get_uv();
        u = w(uv) -  dt * pg(gid)/density;
    }
    imageStore(div_free_vector_field_u, gid, vec4(u.x));
    imageStore(div_free_vector_field_v, gid, vec4(u.y));
}
