#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#define COLLISION_SET 8
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler3D vector_field_u;
layout(set = 2, binding = 0) uniform sampler3D vector_field_v;
layout(set = 3, binding = 0) uniform sampler3D vector_field_w;
layout(set = 4, binding = 0) uniform sampler3D pressure_field;
layout(set = 5, binding = 2) uniform writeonly image3D div_free_vector_field_u;
layout(set = 6, binding = 2) uniform writeonly image3D div_free_vector_field_v;
layout(set = 7, binding = 2) uniform writeonly image3D div_free_vector_field_w;

float p(ivec3 cell) {
    return texelFetch(pressure_field, collisionSampleCoord(cell), 0).x;
}

float p(ivec3 centerCell, ivec3 sampleCell) {
    if (outOfBounds(sampleCell)) {
        return 0.0;
    }

    if (isInsideWall(sampleCell)) {
        return p(centerCell);
    }

    return p(sampleCell);
}

vec3 w(vec3 xyz) {
    vec3 u;
    u.x = texture(vector_field_u, xyz).x;
    u.y = texture(vector_field_v, xyz).x;
    u.z = is3D ? texture(vector_field_w, xyz).x : 0.0;
    return u;
}

vec3 pg(ivec3 cell){
    float dudx = (p(cell, cell + ivec3(1, 0, 0)) - p(cell, cell - ivec3(1, 0, 0)))/(2*dx.x);
    float dudy = (p(cell, cell + ivec3(0, 1, 0)) - p(cell, cell - ivec3(0, 1, 0)))/(2*dy.y);
    float dudz = is3D ? (p(cell, cell + ivec3(0, 0, 1)) - p(cell, cell - ivec3(0, 0, 1)))/(2*dz.z) : 0.0;

    return vec3(dudx, dudy, dudz);
}

void main() {
    if(outOfBounds()) return;


    vec3 u = vec3(0);
    if(!isInsideWall(gid3)) {
        vec3 uv = get_uvw();
        u = w(uv) -  dt * pg(gid3)/density;
    }
    imageStore(div_free_vector_field_u, gid3, vec4(u.x));
    imageStore(div_free_vector_field_v, gid3, vec4(u.y));
    imageStore(div_free_vector_field_w, gid3, vec4(u.z));
}
