#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler3D vector_field_u;
layout(set = 2, binding = 0) uniform sampler3D vector_field_v;
layout(set = 3, binding = 1) uniform texture3D quantity;
layout(set = 4, binding = 2) uniform writeonly image3D quantity_out;
layout(set = 5, binding = 0) uniform sampler aSampler;

vec2 loadVectorField(vec2 uv) {
    vec2 u;
    vec3 sampleUv = vec3(uv, 0.5);
    u.x = texture(vector_field_u, sampleUv).x;
    u.y = texture(vector_field_v, sampleUv).x;

    return u;
}


vec4 getQuantity(vec2 xy) {
    return texture(sampler3D(quantity, aSampler), vec3(xy, 0.5));
}

void updateQuantity(vec4 q) {
    imageStore(quantity_out, gid3, q);
}

void main() {
    if(outOfBounds()) return;

    vec2 uv = get_uv();
    vec2 u = loadVectorField(uv);

    vec4 q = getQuantity(uv);

    vec2 p = uv + dt * u;
    ivec3 loc = ivec3(ivec2(floor(p * vec2(grid_size.xy))), gid3.z);
    imageStore(quantity_out, loc, q);
}
