#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#define BOUNDARY_SET 4
#include "common_new.glsl"

layout(set = 1, binding = 0) uniform sampler2D solution;
layout(set = 2, binding = 0) uniform sampler2D unknown;
layout(set = 3, binding = 2) uniform writeonly image2D unknow_image;

layout(push_constant, scalar) uniform Constants {
    float alpha;
    float rBeta;
    uint is_vector_field;
    uint pass;
};

vec4 b(vec2 coord){
    vec4 _b = texture(solution, coord);
//    if(is_vector_field == 1){
//        return applyBoundaryCondition(coord, _b);
//    }
    return _b;
}

vec4 x0(vec2 centerUv, vec2 coord){
    vec4 _x0 = texture(unknown, scalarBoundarySampleUv(centerUv, coord));
    _x0.x = reflectVelocityComponentAtBoundary(_x0.x, is_vector_field, centerUv, coord);
    return _x0;
}
void main() {
    vec2 uv = get_uv();
    if(outOfBounds()) return;
    if(checkBoundary(uv)){
        imageStore(unknow_image, gid, vec4(0));
        return;
    }

    float dxdx = dx.x * dx.x;
    float dydy = dy.y * dy.y;
    vec4 x = ((x0(uv, uv + dx) + x0(uv, uv - dx)) * dydy + (x0(uv, uv + dy) + x0(uv, uv - dy)) * dxdx + alpha * b(uv)) * rBeta;

    imageStore(unknow_image, gid, x);
}
