#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 8, local_size_y = 8) in;

#define COLLISION_SET 4
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler3D vorticity_field;
layout(set = 2, binding = 0) uniform sampler3D force_field;
layout(set = 3, binding = 2) uniform writeonly image3D force_field_out;

layout(push_constant) uniform Constants{
    float csCale;
};

float vort(vec3 coord) {
    return texture(vorticity_field, coord).x;
}

vec3 vort3(vec3 coord) {
    return texture(vorticity_field, coord).xyz;
}

float vortMag(vec3 coord) {
    return is3D ? length(vort3(coord)) : abs(vort(coord));
}

vec3 accumForce(vec3 coord){
    vec4 force = texture(force_field, coord);
    return vec3(force.xy, is3D ? force.z : 0.0);
}

void applyVorticity2D(vec3 uv) {
    float dudx = (vortMag(uv + dx) - vortMag(uv - dx))/(2*dx.x);
    float dudy = (vortMag(uv + dy) - vortMag(uv - dy))/(2*dy.y);

    vec2 n = vec2(dudx, dudy);

    // safe normalize
    float epsilon = 2.4414e-4;
    float magSqr = max(epsilon, dot(n, n));
    n = n * inversesqrt(magSqr);

    float vc = vort(uv);
    float cellSize = min(dx.x, dy.y);
    vec2 force = csCale * cellSize * vc * vec2(n.y, -n.x) + accumForce(uv).xy;

    imageStore(force_field_out, gid3, vec4(force, 0, 0));
}

void applyVorticity3D(vec3 uv) {
    float dwdx = (vortMag(uv + dx) - vortMag(uv - dx))/(2*dx.x);
    float dwdy = (vortMag(uv + dy) - vortMag(uv - dy))/(2*dy.y);
    float dwdz = (vortMag(uv + dz) - vortMag(uv - dz))/(2*dz.z);

    vec3 n = vec3(dwdx, dwdy, dwdz);

    // safe normalize
    float epsilon = 2.4414e-4;
    float magSqr = max(epsilon, dot(n, n));
    n = n * inversesqrt(magSqr);

    float cellSize = max(dx.x, max(dy.y, dz.z));
    vec3 force = accumForce(uv) + cellSize * csCale * cross(n, vort3(uv));

    imageStore(force_field_out, gid3, vec4(force, 0));
}

void main(){
    if(outOfBounds()) return;

    vec3 uv = get_uvw();

    if(is3D) {
        applyVorticity3D(uv);
    } else {
        applyVorticity2D(uv);
    }
}
