#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#define BOUNDARY_SET 4
#include "common.glsl"

layout(set = 1, binding = 0) uniform sampler2D vorticity_field;
layout(set = 2, binding = 0) uniform sampler2D force_field;
layout(set = 3, binding = 2) uniform writeonly image2D force_field_out;

layout(push_constant) uniform Constants{
    float csCale;
};

float vort(vec2 centerUv, vec2 coord) {
    return texture(vorticity_field, scalarBoundarySampleUv(centerUv, coord)).x;
}

vec2 accumForce(vec2 coord){
    return texture(force_field, coord).xy;
}

void main(){
    if(outOfBounds()) return;

    vec2 uv = get_uv();
    if(checkBoundary(uv)){
        imageStore(force_field_out, gid, vec4(0));
        return;
    }

    float dudx = (abs(vort(uv, uv + dx)) - abs(vort(uv, uv - dx)))/(2*dx.x);
    float dudy = (abs(vort(uv, uv + dy)) - abs(vort(uv, uv - dy)))/(2*dy.y);

    vec2 n = vec2(dudx, dudy);

    // safe normalize
    float epsilon = 2.4414e-4;
    float magSqr = max(epsilon, dot(n, n));
    n = n * inversesqrt(magSqr);

    float vc = vort(uv, uv);
    vec2 eps = (dx + dy) * csCale;
    vec2 force = eps * vc * n * vec2(1, -1) + accumForce(uv);

    imageStore(force_field_out, gid, vec4(force, 0, 0));
}
