#version 460
#extension GL_EXT_scalar_block_layout : enable
#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_nonuniform_qualifier : enable

layout(local_size_x = 32, local_size_y = 32) in;

#define BOUNDARY_SET 4
#include "common_new.glsl"

layout(set = 1, binding = 0) uniform sampler2D vector_field_u;
layout(set = 2, binding = 0) uniform sampler2D vector_field_v;
layout(set = 3, binding = 2) uniform writeonly image2D vorticity_field;

vec2 u(vec2 centerUv, vec2 sampleUv) {
    vec2 coord = scalarBoundarySampleUv(centerUv, sampleUv);
    vec2 u;
    u.x = texture(vector_field_u, coord).x;
    u.y = texture(vector_field_v, coord).x;

    return reflectVelocityAtBoundary(u, centerUv, sampleUv);
}


void main(){
    if(outOfBounds()) return;

    vec2 uv = get_uv();
    if(checkBoundary(uv)){
        imageStore(vorticity_field, gid, vec4(0));
        return;
    }

    float dudx = (u(uv, uv + dx).x - u(uv, uv - dx).x)/(2*dx.x);
    float dudy = (u(uv, uv + dy).y - u(uv, uv - dy).y)/(2*dy.y);

    float vorticity = dudy - dudx;

    imageStore(vorticity_field, gid, vec4(vorticity));
}
